"use client"
import '@/style/reset.scss'
import '@/style/global.scss'
import 'react-toastify/dist/ReactToastify.css';
import { Inter } from 'next/font/google'
import { ToastContainer } from 'react-toastify'

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}
const inter = Inter({ subsets: ['latin'] })
export default function RootLayout({ children }) {
  return (
    <html lang="en" className={inter.className}>
      <body>
        <div area-hidden="true" className='overlay' />
        {children}
        <ToastContainer theme='dark'/>
        </body>
    </html>
  )
}
